# Import the relevant libraries

In [1]:
import numpy as np

## Addition

In [2]:
m1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
m2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
m1 + m2

array([[ 8, 10, 12],
       [14, 16, 18]])

## Difference

In [5]:
m1 - m2

array([[-6, -6, -6],
       [-6, -6, -6]])

## Adding vectors together

In [6]:
v1 = np.array([1, 2, 3])

In [7]:
v2 = np.array([4, 5, 6])

In [8]:
v1 + v2

array([5, 7, 9])