## Import relevant libraries

In [2]:
import numpy as np

## Dot product

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x, y

(array([1, 2, 3]), array([4, 5, 6]))

In [4]:
np.dot(x,y)

32

## Scalar * Scalar

In [5]:
np.dot(2,4)

8

## Scalar * Vector

In [6]:
x

array([1, 2, 3])

In [7]:
x * 2

array([2, 4, 6])

## Scalar * Matrix

In [12]:
m1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
m1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## Matrix * Matrix

In [10]:
m2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [14]:
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])