# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors, and matrices

## Scalars

In [2]:
s = 1

In [3]:
s

1

## Vectors

In [4]:
v = np.array([1, 2, 3])

In [5]:
v

array([1, 2, 3])

## Matrices

In [6]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [7]:
m

array([[1, 2, 3],
       [4, 5, 6]])

## Data types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

## Data shapes

In [11]:
np.array(s).shape

()

In [12]:
v.shape

(3,)

In [13]:
m.shape

(2, 3)

## Creating a column vector

In [14]:
v.reshape((3, 1))

array([[1],
       [2],
       [3]])