# Import the relevant libraries

In [1]:
import numpy as np

## Creating a tensor

In [2]:
m1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
m2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
t = np.array([m1, m2])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Checking its shape

In [5]:
t.shape

(2, 2, 3)

## Manually creating a tensor

In [6]:
t_manual = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
t_manual

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])