# Import the relevant libraries

In [1]:
import numpy as np

## Transposing matrices

In [2]:
m1 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
m1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Transposing scalars

In [4]:
s = np.array([1])

In [5]:
s.T

array([1])

## Transposing vectors

In [6]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [7]:
v.T

array([1, 2, 3])

In [8]:
v.shape

(3,)

In [9]:
v_reshaped = v.reshape(1,3)
v_reshaped

array([[1, 2, 3]])

In [10]:
v_reshaped.T

array([[1],
       [2],
       [3]])